function pathname=printnumofisafeaturepath(sample_fg,config) 
pathdict = config.rfdis3d.path.saveisadictionaries;
if strcmp(sample_fg,'train')
    pathname = fullfile(pathdict,['sum_' num2str(config.rfdis3d.class.num) '_sample_'...
                         num2str(config.rfdis3d.data.tr.st) '_t_' num2str(config.rfdis3d.data.tr.ed)...
                         '_' num2str(config.isa.l2.imagesize) '_size_' num2str(config.isa.l2.tempesize)...
                         '_' num2str(config.isa.ds.imagestride) '_stride_' num2str(config.isa.ds.tempestride) '.mat']);
elseif strcmp(sample_fg,'test')
    pathname = fullfile(pathdict,['sum_' num2str(config.rfdis3d.class.num) '_sample_'...
                         num2str(config.rfdis3d.data.te.st) '_t_' num2str(config.rfdis3d.data.te.ed)...
                         '_' num2str(config.isa.l2.imagesize) '_size_' num2str(config.isa.l2.tempesize)...
                         '_' num2str(config.isa.ds.imagestride) '_stride_' num2str(config.isa.ds.tempestride) '.mat']);  
    
end